# Generated by Django 3.1 on 2020-10-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_category_comments_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
