# Generated by Django 3.1 on 2020-10-07 10:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_comment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlisted',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
